spring.application.name=chaos-engineering-toxiproxy
spring.datasource.url=jdbc:postgresql://localhost:5432/chaos
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=update
