spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/rlsdb
    username: myuser
    password: mypassword
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always
