spring.application.name=cqrs-event-sourcing
spring.datasource.url=jdbc:postgresql://localhost:5432/cqrs
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=update
