spring.application.name=tdd-zero-mocking
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:postgresql://localhost:5432/demo
spring.datasource.username=test
spring.datasource.password=test
spring.jpa.properties.hibernate.format_sql=true
